top_srcdir    ?= ../..
include $(top_srcdir)/include/mk/env_pre.mk
SUBDIRS := ethernet/
SUBDIRS += gy521_id/
SUBDIRS += rtc/
SUBDIRS += spi/

include $(top_srcdir)/include/mk/generic_trunk_target.mk

