top_srcdir    ?= ../..
include $(top_srcdir)/include/mk/env_pre.mk
SUBDIRS := audio_playback_test/
SUBDIRS += cpu_core_test/
SUBDIRS += ethernet/
SUBDIRS += gpio_test/
SUBDIRS += gy521_id/
SUBDIRS += rtc/
SUBDIRS += spi/
SUBDIRS += wdt_test/

include $(top_srcdir)/include/mk/generic_trunk_target.mk

